info:
  app:
    name: todo-list-service

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username:
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true

server:
  port: 8080
